# Generated by Django 2.1.1 on 2018-09-27 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=30, null=True)),
                ('cust_mobile', models.CharField(max_length=30, unique=True)),
                ('cust_address', models.CharField(max_length=50, null=True)),
                ('message', models.TextField(null=True)),
                ('visit_record', models.TextField(null=True)),
                ('next_visit_date', models.DateField(null=True)),
                ('type', models.IntegerField()),
                ('source_tag', models.CharField(max_length=50, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('follow_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_user', to=settings.AUTH_USER_MODEL)),
                ('last_follow_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_follow_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
    ]
