# Generated by Django 2.1.1 on 2018-09-27 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custmessage',
            name='last_follow_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_follow_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
