# Generated by Django 2.1.1 on 2018-09-27 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message_core', '0003_auto_20180927_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custmessage',
            name='cust_address',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='custmessage',
            name='cust_name',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='custmessage',
            name='last_follow_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_follow_user', to='message_core.UserProfile', to_field='user_num'),
        ),
        migrations.AlterField(
            model_name='custmessage',
            name='message',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='custmessage',
            name='next_visit_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='custmessage',
            name='source_tag',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='custmessage',
            name='visit_record',
            field=models.TextField(default=None, null=True),
        ),
    ]
